<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NAG-MAC" ignored="0" name="calc-add" tests="3" failures="2" timestamp="2020-02-21T16:42:00 IST" time="2.28" errors="0">
  <testcase name="add100And200" time="0.239" classname="com.example.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [300] but found [3003]">
      <![CDATA[java.lang.AssertionError: expected [300] but found [3003]
at com.example.CalculatorTest.add100And200(CalculatorTest.java:96)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- add100And200 -->
  <testcase name="add1And2" time="0.232" classname="com.example.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [3] but found [3003]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [3003]
at com.example.CalculatorTest.add1And2(CalculatorTest.java:54)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- add1And2 -->
  <testcase name="add10And20" time="0.121" classname="com.example.CalculatorTest"/>
</testsuite> <!-- calc-add -->
